### ISSUE TITLE
Unable to assign config file

### ISSUE THREAD

**Issue by pratikp09** [raintank/statsdaemon#24] opened 2017-01-20 20:18 UTC
Hi 

I had a statsdaemon running on my server 2 days back. It was having issues sending metrics so I decided to reinstall it. But ever since I trying to assign a config file to it, I am getting the below error

_Could not read config file: /tmp/statsdaemon/statsdaemon.ini is not a valid TOML file. See https://github.com/mojombo/toml_

I see a couple of commits made yesterday. Is anyone seeing the same issue

**Comment by ehlerst** [comment] 2017-01-20 22:50
New config lines were added that do not exist
```
#prefix_m20_rates = ""
#prefix_m20_counters = ""
#prefix_m20_timers = ""
#prefix_m20_gauges = ""
```

**Comment by ehlerst** [comment] 2017-01-21 03:29
So the issue seems to be the numbers in the key. 

put this in the ini file
`prefix_m20 = "dasf"`

```
../build/statsdaemon -config_file statsdaemon.ini  -debug
Could not read config file: **prefix_m** is not a valid config setting
```

So for some reason the numbers are getting lopped off.

**Comment by Dieterbe** [comment] 2017-01-22 12:01
looks like there was a bug in the toml library we're using.
As per commit above, it should be fixed now. please confirm.

**Comment by Dieterbe** [comment] 2017-01-22 14:07
confirmed solved.

**Closed by Dieterbe** 2017-01-22 14:07 UTC
